apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
 labels:
   service: nginx-service
 name: nginx-deployment
spec:
 type: NodePort
 ports:
 - name: nginx-deployment
   protocol: TCP
   port: 80
   targetPort: 80
 selector:
   app: nginx
